packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'

catalog:
  "@types/jest": ^29.5.2
  "@types/node": ^24.0.0
  jest: ^30.0.0
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.1
  ts-jest: ^29.3.4
  typescript: ^5.8.3
  
catalogs:
  nestjs@10:
    "@nestjs/cli": ^10.0.0
    "@nestjs/common": ^10.0.0
    "@nestjs/core": ^10.0.0
    "@nestjs/microservices": ^10.2.2
    "@nestjs/platform-express": ^10.0.0
    "@nestjs/schematics": ^10.0.0
    "@nestjs/testing": ^10.0.0
