packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'

catalog:
  "@types/node": "^24.0.0"
  typescript: ^5.8.3
  
catalogs:
  nestjs@10:
    "@nestjs/cli": "^10.0.0"
    "@nestjs/common": "^10.0.0"
    "@nestjs/core": "^10.0.0"
    "@nestjs/microservices": "^10.2.2"
    "@nestjs/platform-express": "^10.0.0"
    "@nestjs/schematics": "^10.0.0"
    "@nestjs/testing": "^10.0.0"