packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'

catalog:
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.1

  jest: ^30.0.0
  prettier: ^3.5.3
  source-map-support: ^0.5.21
  supertest: ^7.1.1
  tsconfig-paths: ^4.2.0
  ts-jest: ^29.3.4
  ts-loader: ^9.5.2
  ts-node: ^10.9.2
  typescript: ^5.8.3

  "@types/express": ^5.0.3
  "@types/jest": ^29.5.2
  "@types/node": ^24.0.0
  "@types/supertest": ^6.0.3

catalogs:
  nestjs@10:
    "@nestjs/cli": ^10.0.0
    "@nestjs/common": ^10.0.0
    "@nestjs/core": ^10.0.0
    "@nestjs/microservices": ^10.2.2
    "@nestjs/platform-express": ^10.0.0
    "@nestjs/schematics": ^10.0.0
    "@nestjs/testing": ^10.0.0
